#!/bin/bash

# This script has been copied and adapted from the following SO answer:
# https://stackoverflow.com/a/54597545
# It is therefore licensed for us under CC-BY-SA:
# https://creativecommons.org/licenses/by-sa/4.0/legalcode
# It is also covered by the entire project's GPLv3 license,
# permitted by the one-way compatibility declaration below:
# https://creativecommons.org/2015/10/08/cc-by-sa-4-0-now-one-way-compatible-with-gplv3/

# Doesn't support comments, but that would be trivial to add
function iniget() {
  if [[ $# -lt 2 ]]; then
    echo "usage: iniget <file> [--list|<section> [key]]"
    return 1
  fi
  if [[ ! -f $1 ]]; then
    echo "Error: No such file $1"
    return 1
  fi
  local inifile=$1

  if [ "$2" == "--list" ]; then
    # [][] below is parsed as a character class containing ][.
    # [\[\]] doesn't work because \ does not escape in a character class.
    grep "\[" "$inifile" | sed "s/[][]//g"
    return 0
  else
    local section=$2
    local key
    [ $# -eq 3 ] && key=$3

    awk '/\[/{prefix=$0; next} $1{print prefix $0}' $inifile | # Flatten the section headers to [section]key = value
      grep "\[${section}\]${key}" |                            # Find all keys in this section
      sed "s/^\[${section}\]//" |                              # Remove the section prefix
      sed "s/^${key}\s*=\s*//"                                 # Remove "key = ", leaving the value
    return 0
  fi
}

iniget "$@"
