#!/bin/bash

##### Parse config file #####

# default location of config file
CONFIG_FILE='$HOME/.config/rbackup/rbackup.ini'
BACKUP_SRC="$(iniget ${CONFIG_FILE} $1 "source")"
BACKUP_DEST="$(iniget ${CONFIG_FILE} $1 "destination")"
ARCHIVE_DEST="$(iniget ${CONFIG_FILE} $1 "remote")"
GPG_RECIPIENT="$(iniget ${CONFIG_FILE} $1 "recipient")"
shift

source rbackup-$1.bash "${@:2}"
